"""Configuration for Spark Code Interpreter backend."""

import json
import os
from pathlib import Path

CONFIG_FILE = Path(__file__).parent / "settings.json"
DEPLOYMENT_CONFIG_FILE = Path(__file__).parent.parent / "config" / "deployment-config.json"

DEFAULT_CONFIG = {
    "global": {
        "bedrock_model": "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        "bedrock_region": "us-east-1",
    },
    "spark": {
        "s3_bucket": "",
        "lambda_function": "",
        "emr_application_id": "",
        "emr_execution_role_arn": "",
        "supervisor_arn": "",
        "code_gen_agent_arn": "",
        "max_retries": 3,
        "file_size_threshold_mb": 100,
        "result_preview_rows": 100,
        "presigned_url_expiry_hours": 24,
        "lambda_timeout_seconds": 300,
        "emr_timeout_minutes": 10,
    },
    "postgres": {
        "connections": [],
        "jdbc_driver_path": "",
    },
}


def _load_deployment_config():
    """Load deployment config generated by deploy-all.sh."""
    if DEPLOYMENT_CONFIG_FILE.exists():
        try:
            with open(DEPLOYMENT_CONFIG_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def load_config():
    """Load merged configuration: defaults < deployment-config < settings.json."""
    config = DEFAULT_CONFIG.copy()

    # Merge deployment config (agent ARNs, S3 bucket, etc.)
    deploy = _load_deployment_config()
    if deploy:
        for section in ("global", "spark", "postgres"):
            if section in deploy:
                if section not in config:
                    config[section] = {}
                config[section].update(deploy[section])

    # Merge user settings (overrides)
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, "r") as f:
                user = json.load(f)
            for section in user:
                if section in config and isinstance(config[section], dict):
                    config[section].update(user[section])
                else:
                    config[section] = user[section]
        except Exception:
            pass

    return config


def save_config(config):
    """Save user settings to settings.json."""
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)


def get_spark_settings():
    """Get Spark-specific settings."""
    return load_config().get("spark", DEFAULT_CONFIG["spark"])


def get_s3_bucket():
    """Get the S3 bucket name."""
    return get_spark_settings().get("s3_bucket", "")
