#!/usr/bin/env python3
"""Test the generated Ray code directly"""

import boto3
import json

def test_generated_code():
    """Test the Ray code generated by the pipeline"""
    
    # The Ray code generated by the pipeline
    ray_code = """import ray

ray.init(address="auto")

@ray.remote
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

@ray.remote
def find_primes(start, end):
    primes = []
    for num in range(start, end):
        if ray.get(is_prime.remote(num)):
            primes.append(num)
    return primes

# Find first 10 prime numbers
primes = []
num = 2
while len(primes) < 10:
    if ray.get(is_prime.remote(num)):
        primes.append(num)
    num += 1

print(f"First 10 prime numbers: {primes}")

ray.shutdown()"""
    
    print("🧪 Testing Generated Ray Code on Ray Cluster")
    print("=" * 60)
    print("📝 Generated Code:")
    print(ray_code)
    print("=" * 60)
    
    # Test via Lambda function
    lambda_client = boto3.client('lambda', region_name='us-east-1')
    
    payload = {
        "code": ray_code,
        "ray_cluster_ip": "172.31.4.12"
    }
    
    try:
        print("🚀 Testing on Ray Cluster...")
        
        response = lambda_client.invoke(
            FunctionName='ray-code-validation',
            Payload=json.dumps(payload)
        )
        
        result = json.loads(response['Payload'].read())
        
        print("📋 Execution Result:")
        print("=" * 40)
        print(json.dumps(result, indent=2))
        
        if result.get('success'):
            print("\n🎉 SUCCESS - Ray code executed successfully!")
            print(f"   Job ID: {result.get('job_id')}")
            print(f"   Status: {result.get('status')}")
        else:
            print(f"\n❌ EXECUTION FAILED: {result.get('error')}")
            
    except Exception as e:
        print(f"❌ Test failed: {e}")

if __name__ == "__main__":
    test_generated_code()
