# Runtime configuration - auto-generated by deploy-backend.sh
import os

def get_config():
    return {
        "spark_supervisor_arn": "arn:aws:bedrock-agentcore:us-east-1:817323390093:runtime/spark_supervisor_agent-kSQUxI8Tqu",
        "code_gen_agent_arn": "arn:aws:bedrock-agentcore:us-east-1:817323390093:runtime/ray_code_interpreter-FKoWFR2k9A",
        "s3_bucket": "spark-data-817323390093-us-east-1",
        "lambda_function": "dev-spark-on-lambda",
        "emr_application_id": "00g20htapo32ta09",
        "region": "us-east-1",
        "account_id": "817323390093"
    }

def load_config():
    return get_config()

def save_config(config):
    pass

def get_ray_private_ip():
    return os.getenv("RAY_PRIVATE_IP", "")

def get_ray_public_ip():
    return os.getenv("RAY_PUBLIC_IP", "")

def get_s3_bucket():
    return "spark-data-817323390093-us-east-1"

def get_default_config():
    return get_config()
